#!/bin/bash

rm "${DBBK_SCRIPT_PATH}my.cnf";
unset DBBK_CONFIG_FILE;
unset DBBK_DAYS;
unset DBBK_FILE;
unset DBBK_FILE_GZ;
unset DBBK_FILE_SIZE;
unset DBBK_FOLDER;
unset DBBK_MINTIME;
unset DBBK_MYSQL_BASE;
unset DBBK_MYSQL_HOST;
unset DBBK_MYSQL_PASS;
unset DBBK_MYSQL_STATUS;
unset DBBK_MYSQL_TEST;
unset DBBK_MYSQL_USER;
unset DBBK_NAME;
unset DBBK_SCRIPT_PATH;
